var builder = DistributedApplication.CreateBuilder(args);

// --------------------
// External Configuration / secrets
// All secrets are pulled from Key Vault in production via managed Identity
//Locally they fall back to user secrets or environment variables.
//-----------------------
var azureOpenAiEndpoint = builder.AddParameter("AzureOpenAiEndpoint", secret: true);
var azureOpenAiApiKey = builder.AddParameter("AzureOpenAiApiKey", secret: true);
var azureOpenAiChatModel = builder.AddParameter("AzureOpenAiChatModel", secret: true);
var azureOpenAiEmbeddingModel = builder.AddParameter("AzureOpenAiEmbeddingModel", secret: true);

//--------------------
// Infrastructure resources

// Qdrant vector database with a data volume for persistence
var qdrant = builder.AddQdrant("qdrant")
                    .WithDataVolume("qdrant-data");
                   // .WithHttpsEndpoint(port:6334, name:"grpc")
                   // .WithEndpoint(port:6333, name:"http");

// Redis - used for semantic query caching and rate-limiting counters
var redis = builder.AddRedis("redis")
                    .WithDataVolume("redis-data");

// Sql server - file index, chat session history
// password is auto-generated by Aspire locally. Injected via key vault in production
var sqlPassword = builder.AddParameter("SqlPassword", secret: true);
var sqlServer = builder.AddSqlServer("sqlserver")
                        .WithDataVolume("sqlserver-data")
                        .WithPassword(sqlPassword)
                        .AddDatabase("ragdb");

// ingestion worker service
// watches the MD files folder, parses, chunks, embeds, upserts to qdrant.
// Runs as a separate container App in production so emdegging worloads do not
// affect API response latency.
var mdFilesPath = builder.AddParameter("MdFilesPath", secret: false);

var ingestion = builder.AddProject<Projects.MdRag_Ingestion>("mdrag-ingestion")
                    .WithReference(qdrant)
                    .WithReference(sqlServer)
                    .WithEnvironment("AzureOpenAI__Endpoint", azureOpenAiEndpoint)
                    .WithEnvironment("AzureOpenAI__ApiKey", azureOpenAiApiKey)
                    .WithEnvironment("AzureOpenAI__EmbeddingModel", azureOpenAiEmbeddingModel)
                    .WithEnvironment("Ingestion__MdFilesRootPath", mdFilesPath)
                    .WaitFor(qdrant)
                    .WaitFor(sqlServer);

//-------------------------
// API - Minimal Api gateway + Agent Framework Pipleline
// ------------------------
var api = builder.AddProject<Projects.MdRag_Api>("mdrag-api")
               .WithReference(qdrant)
               .WithReference(redis)
               .WithReference(sqlServer)
                .WithEnvironment("AzureOpenAI__Endpoint", azureOpenAiEndpoint)
                .WithEnvironment("AzureOpenAI__ApiKey", azureOpenAiApiKey)
                .WithEnvironment("AzureOpenAI__ChatModel", azureOpenAiChatModel)
                .WithEnvironment("AzureOpenAI__EmbedModel", azureOpenAiEmbeddingModel)
                .WaitFor(qdrant)
                .WaitFor(redis)
                .WaitFor(sqlServer)
                .WaitForCompletion(ingestion); // ensure API does not start until initial ingestion is complete

//-------------------------
// Frontend - Blazor WebAssembly app that calls the API
//--------------------------
builder.AddProject<Projects.MdRag_Web>("mdrag-web")
        .WithReference(api)     // API project reference to ensure it is built first and to pull in any shared configuration
        .WithExternalHttpEndpoints() // allow this project to call the API via HTTP, and to be called from the browser, but do not create an internal endpoint for it as it will be served statically in production via Azure Static Web Apps
        .WaitFor(api);


await builder.Build().RunAsync();
