using System;
using System.Collections.Generic;
using System.Text;

namespace McpGateway.Core.Models;

/// <summary>
/// Everything the gateway needs to route, validate and dispatch one tool call.
/// Immutable record - middlewares creates copies rather than mutating.
/// </summary>
public record McpToolCallRequest
{
    /// <summary>
    /// Unique ID for this invocation. Generated by the gateway if the caller omits it
    /// </summary>
    public required string CorrelationId { get; init; }

    /// <summary>
    /// Logical identity of the calling agent (e.g. "it-support-agent").
    /// </summary>
    public required string AgentId { get; init; }
    /// <summary>
    /// ID of the target MCP server as registered in the gateway (e.g. "it-support-mcp").
    /// </summary>
    public required string ServerId { get; init; }
    /// <summary>
    /// Tool name within the server (e.g. "get_open_incidents"). 
    /// The gateway uses this to route the request to the correct server and tool.
    /// </summary>
    public required string ToolName { get; init; }
    /// <summary>
    /// RAW JSON arguments from agent that will be pass to the tool. 
    /// The gateway does no validation or transformation on this - it's just a string blob to the server.
    /// </summary>
    public required Dictionary<string,object?> Arguments { get; init; }

    public DateTimeOffset ReceivedAt { get; init; } = DateTimeOffset.UtcNow;
}
